### PR TITLE
Adding code to allow reading of 1D^2 outputs

### PR DESCRIPTION
**Pull request by tanaes**
I added a few things to allow reading 1D^2 output files from Albacore. 

Essentially all I'm doing is catching the AssertionError if the required columns don't exist, and then making some rough approximations of the values not included (duration and num_events) to allow all downstream code to work.

The *right* way might be change other functions to be aware of data type, or to recode them in such a way as to not require those values. But I'll leave that to you if you're so inspired!

Note that the included example file is too small to generate plots that are hardcoded to resample 50k points without replacement (e.g. pycoQC.py line #167; suggest changing this to `.sample(50000, replace=True)` to fix.

### CODE REVIEW

**Comment by a-slide** [comment]
Thanks for your suggestions Jon,
Would you mind resubmitting the pull request to me dev fork (https://github.com/a-slide/pycoQC)
I can't find a way to transfer it. I will mention it in the README

Thanks

Adrien

**Comment by a-slide** [comment]
I found a way to do it via command line, but I have to close the pull request
I will review the changes and resubmit a new version ASAP.

Thanks

**Comment by a-slide** [comment]
Done. I followed your recommendations and did a pretty extensive refactoring of the code to cope with 1d2 files.
Thanks

**Comment by tanaes** [comment]
Cool! Glad it was useful!

**Pull request closed without merging**
